const items =[
    {
        id:'001',
        item_image1:'puma12c.avif',
        item_image2:'puma12d.avif',
        item_image3:'puma12f.avif',
        item_image4:'puma12g.avif',
        product_size_no:38,
        prise_box:{
          current_prise:629,
          original_prise:1499,
          discount:58
        },

     },
    {
        id:'002',
        item_image1:'puma12c.avif',
        item_image2:'puma12d.avif',
        item_image3:'puma12f.avif',
        item_image4:'puma12g.avif',
        product_size_no:38,
        prise_box:{
          current_prise:629,
          original_prise:1499,
          discount:58
        },
     },
    {
        id:'003',
        item_image1:'puma12c.avif',
        item_image2:'puma12d.avif',
        item_image3:'puma12f.avif',
        item_image4:'puma12g.avif',
        product_size_no:38,
        prise_box:{
          current_prise:629,
          original_prise:1499,
          discount:58
        },
     },
    {
        id:'004',
        item_image1:'puma12c.avif',
        item_image2:'puma12d.avif',
        item_image3:'puma12f.avif',
        item_image4:'puma12g.avif',
        product_size_no:38,
        prise_box:{
          current_prise:629,
          original_prise:1499,
          discount:58
        },
     },
    {
        id:'005',
        item_image1:'puma12c.avif',
        item_image2:'puma12d.avif',
        item_image3:'puma12f.avif',
        item_image4:'puma12g.avif',
        product_size_no:38,
        prise_box:{
          current_prise:629,
          original_prise:1499,
          discount:58
        },
     },
    {
        id:'006',
        item_image1:'puma12c.avif',
        item_image2:'puma12d.avif',
        item_image3:'puma12f.avif',
        item_image4:'puma12g.avif',
        product_size_no:38,
        prise_box:{
          current_prise:629,
          original_prise:1499,
          discount:58
        },
     },
    {
        id:'007',
        item_image1:'puma12c.avif',
        item_image2:'puma12d.avif',
        item_image3:'puma12f.avif',
        item_image4:'puma12g.avif',
        product_size_no:38,
        prise_box:{
          current_prise:629,
          original_prise:1499,
          discount:58
        },
     },
    {
        id:'008',
        item_image1:'puma12c.avif',
        item_image2:'puma12d.avif',
        item_image3:'puma12f.avif',
        item_image4:'puma12g.avif',
        product_size_no:38,
        prise_box:{
          current_prise:629,
          original_prise:1499,
          discount:58
        },
     },


]